/* AMS TechLingo — built-in starter library (~205 terms).
   Seeded ONCE on first launch; after that every entry lives in the database
   and is fully editable. Editing here later does NOT change an already-seeded
   device — that is deliberate, so user edits are never overwritten. */

const TL_LIBRARY = (() => {
    const HW = 'Hardware & Devices';
    const WEB = 'Web & Internet';
    const SW = 'Software & Apps';
    const AI = 'AI';
    const CLOUD = 'Cloud & Data';
    const SEC = 'Security & Privacy';
    const NET = 'Networking';
    const APPLE = 'Mac & iPhone';
    const DEV = 'Development & Code';

    return [
    // ---------- Development & Code ----------
    {t:'API', c:DEV,
     en:'Application Programming Interface — a set of rules that lets one program talk to another, like a waiter carrying orders between you and the kitchen.',
     de:'Eine Schnittstelle, über die ein Programm mit einem anderen kommunizieren kann — wie ein Kellner zwischen Gast und Küche.',
     sv:'Ett gränssnitt som låter ett program prata med ett annat — som en kypare mellan gästen och köket.'},
    {t:'Repository (Repo)', c:DEV,
     en:'A storage place for a project’s code and its full change history, usually hosted on a service like GitHub.',
     de:'Ein Speicherort für den Code eines Projekts samt seiner gesamten Änderungshistorie, meist auf GitHub.',
     sv:'En lagringsplats för ett projekts kod och hela dess ändringshistorik, oftast på GitHub.'},
    {t:'Git', c:DEV,
     en:'The most widely used version-control system. It records every change to files so you can look back or undo.',
     de:'Das am weitesten verbreitete Versionskontrollsystem — es protokolliert jede Änderung an Dateien.',
     sv:'Det mest använda versionshanteringssystemet — det registrerar varje ändring i filerna.'},
    {t:'GitHub', c:DEV,
     en:'A website that hosts Git repositories online, so code can be stored, shared and published (e.g. as GitHub Pages websites).',
     de:'Eine Website, die Git-Repositories online speichert, teilt und veröffentlicht (z. B. als GitHub-Pages-Websites).',
     sv:'En webbplats som lagrar Git-repositorier online så att kod kan delas och publiceras (t.ex. som GitHub Pages).'},
    {t:'Commit', c:DEV,
     en:'A saved snapshot of changes in Git, with a short message describing what changed.',
     de:'Ein gespeicherter Schnappschuss von Änderungen in Git, mit kurzer Beschreibung.',
     sv:'En sparad ögonblicksbild av ändringar i Git, med ett kort meddelande.'},
    {t:'Push', c:DEV,
     en:'Uploading your local commits to the online repository so they become visible there.',
     de:'Das Hochladen lokaler Commits ins Online-Repository, damit sie dort sichtbar werden.',
     sv:'Att ladda upp lokala commits till online-repositoriet så att de syns där.'},
    {t:'Pull', c:DEV,
     en:'Downloading the latest changes from the online repository to your own computer.',
     de:'Das Herunterladen der neuesten Änderungen aus dem Online-Repository auf den eigenen Rechner.',
     sv:'Att hämta de senaste ändringarna från online-repositoriet till din egen dator.'},
    {t:'Branch', c:DEV,
     en:'A separate line of development in a repository, used to try changes without touching the main version.',
     de:'Ein separater Entwicklungszweig in einem Repository, um Änderungen auszuprobieren, ohne die Hauptversion anzufassen.',
     sv:'En separat utvecklingsgren i ett repositorium, för att testa ändringar utan att röra huvudversionen.'},
    {t:'Merge', c:DEV,
     en:'Combining the changes from one branch into another, typically back into the main branch.',
     de:'Das Zusammenführen der Änderungen eines Zweigs in einen anderen, meist zurück in den Hauptzweig.',
     sv:'Att slå ihop ändringar från en gren till en annan, oftast tillbaka till huvudgrenen.'},
    {t:'Pull Request (PR)', c:DEV,
     en:'A proposal on GitHub to merge one set of changes into a project, which others can review first.',
     de:'Ein Vorschlag auf GitHub, Änderungen in ein Projekt zu übernehmen, den andere vorher prüfen können.',
     sv:'Ett förslag på GitHub om att föra in ändringar i ett projekt, som andra kan granska först.'},
    {t:'Bug', c:DEV,
     en:'An error in software that makes it behave incorrectly or crash.',
     de:'Ein Fehler in Software, der zu falschem Verhalten oder Abstürzen führt.',
     sv:'Ett fel i programvara som gör att den beter sig fel eller kraschar.'},
    {t:'Debugging', c:DEV,
     en:'The process of finding and fixing bugs in software.',
     de:'Das Aufspüren und Beheben von Fehlern in Software.',
     sv:'Att hitta och rätta fel i programvara.'},
    {t:'Frontend', c:DEV,
     en:'The part of an app or website the user sees and interacts with — buttons, lists, colours.',
     de:'Der Teil einer App oder Website, den der Nutzer sieht und bedient — Knöpfe, Listen, Farben.',
     sv:'Den del av en app eller webbplats som användaren ser och använder — knappar, listor, färger.'},
    {t:'Backend', c:DEV,
     en:'The invisible part of an app that runs on a server: data storage, logic and calculations behind the scenes.',
     de:'Der unsichtbare Teil einer App auf einem Server: Datenspeicherung und Logik hinter den Kulissen.',
     sv:'Den osynliga delen av en app som körs på en server: datalagring och logik bakom kulisserna.'},
    {t:'Framework', c:DEV,
     en:'A pre-built foundation of code that developers build apps on top of, so they don’t start from zero.',
     de:'Ein vorgefertigtes Code-Grundgerüst, auf dem Entwickler Apps aufbauen, statt bei null zu beginnen.',
     sv:'En färdig kodgrund som utvecklare bygger appar ovanpå, så att de slipper börja från noll.'},
    {t:'Library (Code)', c:DEV,
     en:'A collection of ready-made code that solves one job (e.g. drawing charts) and can be reused in many apps.',
     de:'Eine Sammlung fertigen Codes für eine bestimmte Aufgabe (z. B. Diagramme), die in vielen Apps wiederverwendet wird.',
     sv:'En samling färdig kod för en viss uppgift (t.ex. diagram) som kan återanvändas i många appar.'},
    {t:'Open Source', c:DEV,
     en:'Software whose code is publicly visible and usually free to use, change and share.',
     de:'Software, deren Code öffentlich einsehbar ist und meist frei genutzt, verändert und geteilt werden darf.',
     sv:'Programvara vars kod är offentlig och oftast fri att använda, ändra och dela.'},
    {t:'IDE', c:DEV,
     en:'Integrated Development Environment — an app for writing code, with editor, testing and debugging tools in one place (e.g. Xcode, VS Code).',
     de:'Eine Entwicklungsumgebung zum Programmieren mit Editor-, Test- und Debug-Werkzeugen in einem (z. B. Xcode, VS Code).',
     sv:'En utvecklingsmiljö för att skriva kod, med redigerare och felsökningsverktyg på samma ställe (t.ex. Xcode, VS Code).'},
    {t:'Terminal', c:DEV,
     en:'An app where you control the computer by typing text commands instead of clicking. On the Mac it’s literally called Terminal.',
     de:'Ein Programm, in dem man den Computer über getippte Textbefehle statt per Klick steuert.',
     sv:'Ett program där man styr datorn med skrivna textkommandon i stället för klick.'},
    {t:'Command Line', c:DEV,
     en:'The text-based way of controlling a computer: you type a command, press Return, and the computer executes it.',
     de:'Die textbasierte Steuerung eines Computers: Befehl eintippen, Enter drücken, der Computer führt ihn aus.',
     sv:'Det textbaserade sättet att styra en dator: skriv ett kommando, tryck Retur, och datorn utför det.'},
    {t:'Script', c:DEV,
     en:'A small program, often a single file, that automates a task — like renaming 100 files at once.',
     de:'Ein kleines Programm, oft eine einzelne Datei, das eine Aufgabe automatisiert — z. B. 100 Dateien umbenennen.',
     sv:'Ett litet program, ofta en enda fil, som automatiserar en uppgift — t.ex. byta namn på 100 filer.'},
    {t:'Syntax', c:DEV,
     en:'The grammar rules of a programming language. A "syntax error" means the code is written in a way the computer can’t read.',
     de:'Die Grammatikregeln einer Programmiersprache. Ein „Syntax Error" heißt: Der Code ist für den Computer unlesbar geschrieben.',
     sv:'Grammatikreglerna i ett programmeringsspråk. Ett "syntax error" betyder att koden är skriven så att datorn inte kan läsa den.'},
    {t:'Variable', c:DEV,
     en:'A named container in code that holds a value which can change — like a labelled box.',
     de:'Ein benannter Behälter im Code, der einen veränderbaren Wert enthält — wie eine beschriftete Box.',
     sv:'En namngiven behållare i kod som håller ett värde som kan ändras — som en märkt låda.'},
    {t:'Function', c:DEV,
     en:'A named block of code that does one job and can be called again and again.',
     de:'Ein benannter Code-Block, der eine Aufgabe erledigt und immer wieder aufgerufen werden kann.',
     sv:'Ett namngivet kodblock som utför en uppgift och kan anropas om och om igen.'},
    {t:'Deploy', c:DEV,
     en:'To publish software so it runs "live" — for example uploading a website so everyone can reach it.',
     de:'Software „live" schalten — z. B. eine Website hochladen, damit alle sie erreichen können.',
     sv:'Att publicera programvara så att den körs "live" — t.ex. ladda upp en webbplats så alla når den.'},
    {t:'Version Control', c:DEV,
     en:'Keeping a history of every change to a project so you can compare, restore or undo. Git is the standard tool.',
     de:'Die Historie aller Projektänderungen führen, um vergleichen und zurückspringen zu können. Git ist das Standardwerkzeug.',
     sv:'Att spara historiken över alla ändringar i ett projekt så att man kan jämföra och ångra. Git är standardverktyget.'},
    {t:'Markdown', c:DEV,
     en:'A simple way to format text using plain characters: *stars* for bold/italic, # for headings. Used in notes apps and on GitHub.',
     de:'Eine einfache Textformatierung mit Zeichen: *Sterne* für fett/kursiv, # für Überschriften. In Notiz-Apps und auf GitHub üblich.',
     sv:'Ett enkelt sätt att formatera text med tecken: *stjärnor* för fet/kursiv, # för rubriker. Vanligt i anteckningsappar och på GitHub.'},
    {t:'JSON', c:DEV,
     en:'A plain-text format for storing structured data, easy for both people and programs to read. Backup files are often JSON.',
     de:'Ein Textformat für strukturierte Daten, gut lesbar für Mensch und Programm. Backup-Dateien sind oft JSON.',
     sv:'Ett textformat för strukturerad data, lätt att läsa för både människor och program. Backupfiler är ofta JSON.'},
    {t:'HTML', c:DEV,
     en:'The language that describes the structure and content of every web page — headings, text, images, links.',
     de:'Die Sprache, die Struktur und Inhalt jeder Webseite beschreibt — Überschriften, Text, Bilder, Links.',
     sv:'Språket som beskriver varje webbsidas struktur och innehåll — rubriker, text, bilder, länkar.'},
    {t:'CSS', c:DEV,
     en:'The language that styles web pages: colours, fonts, spacing and layout.',
     de:'Die Sprache, die Webseiten gestaltet: Farben, Schriften, Abstände, Layout.',
     sv:'Språket som formger webbsidor: färger, typsnitt, avstånd och layout.'},
    {t:'JavaScript', c:DEV,
     en:'The programming language of the web — it makes pages interactive (buttons, lists, saving data). Not related to Java.',
     de:'Die Programmiersprache des Webs — sie macht Seiten interaktiv. Hat nichts mit Java zu tun.',
     sv:'Webbens programmeringsspråk — det gör sidor interaktiva. Har inget med Java att göra.'},
    {t:'Python', c:DEV,
     en:'A popular, beginner-friendly programming language, widely used for automation, data and AI.',
     de:'Eine beliebte, einsteigerfreundliche Programmiersprache, viel genutzt für Automatisierung, Daten und KI.',
     sv:'Ett populärt och nybörjarvänligt programmeringsspråk, ofta använt för automatisering, data och AI.'},
    {t:'SDK', c:DEV,
     en:'Software Development Kit — a toolbox a company provides so developers can build apps for its platform.',
     de:'Ein Werkzeugkasten, den eine Firma bereitstellt, damit Entwickler Apps für ihre Plattform bauen können.',
     sv:'En verktygslåda som ett företag tillhandahåller så att utvecklare kan bygga appar för dess plattform.'},
    {t:'Localhost', c:DEV,
     en:'Your own computer acting as a web server, reachable only from itself — used to test websites before publishing.',
     de:'Der eigene Rechner als Webserver, nur von sich selbst erreichbar — zum Testen von Websites vor der Veröffentlichung.',
     sv:'Din egen dator som webbserver, bara nåbar från sig själv — används för att testa webbplatser före publicering.'},
    {t:'Refactoring', c:DEV,
     en:'Rewriting code to make it cleaner and easier to maintain, without changing what it does.',
     de:'Code umschreiben, damit er sauberer und wartbarer wird, ohne sein Verhalten zu ändern.',
     sv:'Att skriva om kod så att den blir renare och lättare att underhålla, utan att ändra vad den gör.'},
    {t:'Changelog', c:DEV,
     en:'A list describing what changed in each version of an app.',
     de:'Eine Liste, die beschreibt, was sich in jeder Version einer App geändert hat.',
     sv:'En lista som beskriver vad som ändrats i varje version av en app.'},
    {t:'Beta', c:DEV,
     en:'A pre-release version of software given to testers: mostly working, but bugs are expected.',
     de:'Eine Vorabversion von Software für Tester: läuft weitgehend, aber Fehler sind zu erwarten.',
     sv:'En förhandsversion av programvara för testare: fungerar mestadels, men buggar väntas.'},
    {t:'Release', c:DEV,
     en:'A finished version of software made available to users, usually with a version number like 2.1.',
     de:'Eine fertige Softwareversion für die Nutzer, meist mit Versionsnummer wie 2.1.',
     sv:'En färdig programversion som görs tillgänglig för användare, oftast med versionsnummer som 2.1.'},

    // ---------- Web & Internet ----------
    {t:'Browser', c:WEB,
     en:'The app you view websites with — Safari, Chrome, Firefox, Edge.',
     de:'Das Programm, mit dem man Websites ansieht — Safari, Chrome, Firefox, Edge.',
     sv:'Programmet du visar webbplatser med — Safari, Chrome, Firefox, Edge.'},
    {t:'URL', c:WEB,
     en:'The address of a web page, e.g. https://www.apple.com. Short for Uniform Resource Locator.',
     de:'Die Adresse einer Webseite, z. B. https://www.apple.com.',
     sv:'Adressen till en webbsida, t.ex. https://www.apple.com.'},
    {t:'Domain', c:WEB,
     en:'The name part of a web address, like apple.com. Domains are rented, not owned forever.',
     de:'Der Namensteil einer Webadresse, z. B. apple.com. Domains werden gemietet, nicht dauerhaft gekauft.',
     sv:'Namndelen av en webbadress, t.ex. apple.com. Domäner hyrs, de ägs inte för alltid.'},
    {t:'HTTP', c:WEB,
     en:'The protocol (set of rules) browsers and web servers use to exchange pages.',
     de:'Das Protokoll (Regelwerk), mit dem Browser und Webserver Seiten austauschen.',
     sv:'Protokollet (regelverket) som webbläsare och webbservrar använder för att utbyta sidor.'},
    {t:'HTTPS', c:WEB,
     en:'The secure, encrypted version of HTTP. The padlock in the address bar means the connection is HTTPS.',
     de:'Die sichere, verschlüsselte Variante von HTTP. Das Schloss in der Adressleiste zeigt HTTPS an.',
     sv:'Den säkra, krypterade varianten av HTTP. Hänglåset i adressfältet betyder HTTPS.'},
    {t:'Cookie', c:WEB,
     en:'A small piece of data a website stores in your browser to remember you — your login, cart or preferences.',
     de:'Ein kleines Datenpaket, das eine Website im Browser ablegt, um sich an dich zu erinnern — Login, Warenkorb, Einstellungen.',
     sv:'En liten databit som en webbplats sparar i din webbläsare för att minnas dig — inloggning, varukorg, inställningar.'},
    {t:'Cache', c:WEB,
     en:'A local copy of already-downloaded data kept for speed. A stale cache is why a website sometimes shows an old version.',
     de:'Eine lokale Kopie bereits geladener Daten für mehr Tempo. Ein veralteter Cache ist der Grund, warum eine Website manchmal alt aussieht.',
     sv:'En lokal kopia av redan hämtad data, sparad för snabbhets skull. En gammal cache är orsaken när en webbplats visar en gammal version.'},
    {t:'Tab', c:WEB,
     en:'One open page inside a browser window; you can keep many tabs open side by side.',
     de:'Eine geöffnete Seite innerhalb eines Browserfensters; viele Tabs können nebeneinander offen sein.',
     sv:'En öppen sida i ett webbläsarfönster; många flikar kan vara öppna samtidigt.'},
    {t:'Bookmark', c:WEB,
     en:'A saved link to a web page so you can return to it quickly.',
     de:'Ein gespeicherter Link zu einer Webseite, um sie schnell wiederzufinden.',
     sv:'En sparad länk till en webbsida så att du snabbt hittar tillbaka.'},
    {t:'Download', c:WEB,
     en:'Copying a file from the internet onto your device.',
     de:'Eine Datei aus dem Internet auf das eigene Gerät kopieren.',
     sv:'Att kopiera en fil från internet till din enhet.'},
    {t:'Upload', c:WEB,
     en:'Sending a file from your device to the internet — e.g. attaching a photo to an email.',
     de:'Eine Datei vom eigenen Gerät ins Internet senden — z. B. ein Foto an eine E-Mail anhängen.',
     sv:'Att skicka en fil från din enhet till internet — t.ex. bifoga ett foto i ett mejl.'},
    {t:'Streaming', c:WEB,
     en:'Playing video or music directly from the internet while it downloads, instead of saving it first.',
     de:'Video oder Musik direkt aus dem Internet abspielen, während es lädt, statt es erst zu speichern.',
     sv:'Att spela video eller musik direkt från internet medan den laddas, i stället för att spara den först.'},
    {t:'Search Engine', c:WEB,
     en:'A service that finds web pages for you — Google, Bing, DuckDuckGo.',
     de:'Ein Dienst, der Webseiten für dich findet — Google, Bing, DuckDuckGo.',
     sv:'En tjänst som hittar webbsidor åt dig — Google, Bing, DuckDuckGo.'},
    {t:'Hyperlink', c:WEB,
     en:'Clickable text or an image that jumps to another page or place. Usually shown underlined or coloured.',
     de:'Klickbarer Text oder ein Bild, das zu einer anderen Seite springt. Meist unterstrichen oder farbig.',
     sv:'Klickbar text eller bild som hoppar till en annan sida. Oftast understruken eller färgad.'},
    {t:'Pop-up', c:WEB,
     en:'A window or box that appears on top of a page by itself, often for ads or cookie questions.',
     de:'Ein Fenster, das sich von selbst über eine Seite legt, oft für Werbung oder Cookie-Abfragen.',
     sv:'Ett fönster som dyker upp ovanpå en sida av sig självt, ofta för reklam eller cookiefrågor.'},
    {t:'Paywall', c:WEB,
     en:'A barrier on a website that hides content until you pay or subscribe.',
     de:'Eine Sperre auf einer Website, die Inhalte erst nach Bezahlung oder Abo zeigt.',
     sv:'En spärr på en webbplats som döljer innehåll tills du betalar eller prenumererar.'},
    {t:'RSS', c:WEB,
     en:'A feed format that lets an app collect new articles from many websites in one list, without visiting each site.',
     de:'Ein Feed-Format, mit dem eine App neue Artikel vieler Websites in einer Liste sammelt.',
     sv:'Ett flödesformat som låter en app samla nya artiklar från många webbplatser i en lista.'},
    {t:'Podcast', c:WEB,
     en:'An audio show published in episodes over the internet that you subscribe to in a podcast app.',
     de:'Eine Audiosendung in Episoden übers Internet, die man in einer Podcast-App abonniert.',
     sv:'Ett ljudprogram i avsnitt via internet som man prenumererar på i en poddapp.'},
    {t:'Web App', c:WEB,
     en:'An app that runs inside the browser instead of being installed from an app store — like Google Docs.',
     de:'Eine App, die im Browser läuft, statt aus einem App Store installiert zu werden — wie Google Docs.',
     sv:'En app som körs i webbläsaren i stället för att installeras från en appbutik — som Google Docs.'},
    {t:'PWA', c:WEB,
     en:'Progressive Web App — a website that behaves like a real app: it gets a home-screen icon, works offline and opens full-screen. All AMS apps are PWAs.',
     de:'Eine Website, die sich wie eine echte App verhält: Home-Bildschirm-Symbol, offline nutzbar, Vollbild. Alle AMS-Apps sind PWAs.',
     sv:'En webbplats som beter sig som en riktig app: ikon på hemskärmen, fungerar offline, öppnas i helskärm. Alla AMS-appar är PWA:er.'},
    {t:'Responsive Design', c:WEB,
     en:'A layout that adapts itself to the screen — the same page looks right on iPhone, iPad and Mac.',
     de:'Ein Layout, das sich dem Bildschirm anpasst — dieselbe Seite sieht auf iPhone, iPad und Mac richtig aus.',
     sv:'En layout som anpassar sig till skärmen — samma sida ser rätt ut på iPhone, iPad och Mac.'},
    {t:'Landing Page', c:WEB,
     en:'A single web page built for one purpose, usually to present a product and get you to act (buy, sign up).',
     de:'Eine einzelne Webseite mit einem Ziel, meist ein Produkt vorstellen und zu einer Aktion führen.',
     sv:'En enskild webbsida med ett syfte, oftast att presentera en produkt och få dig att agera.'},
    {t:'Favicon', c:WEB,
     en:'The tiny icon of a website shown in the browser tab and in bookmarks.',
     de:'Das kleine Symbol einer Website im Browser-Tab und in Lesezeichen.',
     sv:'Den lilla ikonen för en webbplats som visas i webbläsarfliken och bland bokmärken.'},
    {t:'404 Error', c:WEB,
     en:'The "page not found" message — the address exists on no page, usually because the link is old or mistyped.',
     de:'Die Meldung „Seite nicht gefunden" — der Link ist veraltet oder falsch getippt.',
     sv:'Meddelandet "sidan hittades inte" — länken är gammal eller felskriven.'},
    {t:'CDN', c:WEB,
     en:'Content Delivery Network — copies of a website’s files stored on servers around the world so pages load fast everywhere.',
     de:'Kopien der Dateien einer Website auf Servern weltweit, damit Seiten überall schnell laden.',
     sv:'Kopior av en webbplats filer på servrar världen över så att sidor laddar snabbt överallt.'},
    {t:'Web Hosting', c:WEB,
     en:'The service of storing a website on a server so it is reachable on the internet.',
     de:'Der Dienst, eine Website auf einem Server bereitzustellen, damit sie im Internet erreichbar ist.',
     sv:'Tjänsten att lagra en webbplats på en server så att den nås via internet.'},
    {t:'GitHub Pages', c:WEB,
     en:'GitHub’s free website hosting: files in a repository are published as a live website at github.io. All AMS apps are published this way.',
     de:'Kostenloses Website-Hosting von GitHub: Dateien eines Repositories werden unter github.io als Website veröffentlicht. Alle AMS-Apps laufen so.',
     sv:'GitHubs gratis webbhotell: filer i ett repositorium publiceras som en webbplats på github.io. Alla AMS-appar publiceras så.'},
    {t:'Private / Incognito Mode', c:WEB,
     en:'A browser window that doesn’t save history, cookies or logins after you close it. It does not make you anonymous to websites.',
     de:'Ein Browserfenster, das nach dem Schließen weder Verlauf noch Cookies speichert. Anonym gegenüber Websites macht es nicht.',
     sv:'Ett webbläsarfönster som inte sparar historik eller cookies när det stängs. Det gör dig inte anonym mot webbplatser.'},

    // ---------- Hardware & Devices ----------
    {t:'CPU', c:HW,
     en:'The processor — the "brain" of a computer that executes all instructions.',
     de:'Der Prozessor — das „Gehirn" des Computers, das alle Befehle ausführt.',
     sv:'Processorn — datorns "hjärna" som utför alla instruktioner.'},
    {t:'GPU', c:HW,
     en:'The graphics processor. Originally for images and games, now also the workhorse behind AI.',
     de:'Der Grafikprozessor. Ursprünglich für Bilder und Spiele, heute auch das Arbeitstier hinter KI.',
     sv:'Grafikprocessorn. Ursprungligen för bilder och spel, numera också arbetshästen bakom AI.'},
    {t:'RAM', c:HW,
     en:'Working memory — the fast, temporary memory a computer uses while running. Empties when powered off.',
     de:'Der Arbeitsspeicher — schneller Zwischenspeicher im Betrieb. Leert sich beim Ausschalten.',
     sv:'Arbetsminnet — det snabba, tillfälliga minne datorn använder när den kör. Töms när strömmen bryts.'},
    {t:'SSD', c:HW,
     en:'Solid State Drive — fast storage with no moving parts. What modern Macs and iPhones store everything on.',
     de:'Schneller Speicher ohne bewegliche Teile. Darauf speichern moderne Macs und iPhones alles.',
     sv:'Snabb lagring utan rörliga delar. Det som moderna Mac-datorer och iPhones lagrar allt på.'},
    {t:'Hard Drive (HDD)', c:HW,
     en:'The older type of storage with spinning magnetic disks — bigger and cheaper than SSDs, but slower.',
     de:'Die ältere Speicherart mit rotierenden Magnetscheiben — größer und günstiger als SSDs, aber langsamer.',
     sv:'Den äldre lagringstypen med snurrande magnetskivor — större och billigare än SSD, men långsammare.'},
    {t:'USB-C', c:HW,
     en:'The current universal connector for charging and data — reversible, so it never goes in "the wrong way".',
     de:'Der aktuelle Universalstecker für Laden und Daten — beidseitig einsteckbar.',
     sv:'Den nuvarande universalkontakten för laddning och data — vändbar, så den passar åt båda hållen.'},
    {t:'HDMI', c:HW,
     en:'The standard cable/connector for sending picture and sound to a TV, monitor or projector.',
     de:'Der Standardanschluss, um Bild und Ton an TV, Monitor oder Beamer zu senden.',
     sv:'Standardkabeln/kontakten för att skicka bild och ljud till TV, skärm eller projektor.'},
    {t:'Bluetooth', c:HW,
     en:'Short-range wireless connection between devices — headphones, keyboards, speakers.',
     de:'Drahtlose Kurzstreckenverbindung zwischen Geräten — Kopfhörer, Tastaturen, Lautsprecher.',
     sv:'Trådlös kortdistansanslutning mellan enheter — hörlurar, tangentbord, högtalare.'},
    {t:'Peripheral', c:HW,
     en:'Any external device plugged into a computer: mouse, keyboard, printer, external drive.',
     de:'Jedes externe Gerät am Computer: Maus, Tastatur, Drucker, externe Festplatte.',
     sv:'Varje extern enhet som kopplas till en dator: mus, tangentbord, skrivare, extern hårddisk.'},
    {t:'Resolution', c:HW,
     en:'How many pixels a screen or image has, e.g. 1920×1080. More pixels = sharper picture.',
     de:'Wie viele Pixel ein Bildschirm oder Bild hat, z. B. 1920×1080. Mehr Pixel = schärferes Bild.',
     sv:'Hur många pixlar en skärm eller bild har, t.ex. 1920×1080. Fler pixlar = skarpare bild.'},
    {t:'Pixel', c:HW,
     en:'One single dot of a digital image or screen. Millions of pixels together form the picture.',
     de:'Ein einzelner Punkt eines digitalen Bildes oder Bildschirms.',
     sv:'En enda punkt i en digital bild eller skärm.'},
    {t:'Firmware', c:HW,
     en:'Software built permanently into a device (router, camera, headphones) that controls its basic functions.',
     de:'Fest in ein Gerät eingebaute Software (Router, Kamera, Kopfhörer), die die Grundfunktionen steuert.',
     sv:'Programvara som är fast inbyggd i en enhet (router, kamera, hörlurar) och styr grundfunktionerna.'},
    {t:'Boot / Reboot', c:HW,
     en:'Booting is starting a computer up; rebooting is restarting it. The classic first fix: "Have you tried turning it off and on again?"',
     de:'Booten heißt hochfahren, Reboot heißt Neustart. Die klassische erste Lösung: aus- und wieder einschalten.',
     sv:'Boot betyder att starta datorn; reboot är omstart. Klassiska första åtgärden: stäng av och sätt på igen.'},
    {t:'Power Cycle', c:HW,
     en:'Turning a device fully off, waiting a few seconds, then on again — often fixes routers and gadgets.',
     de:'Ein Gerät ganz ausschalten, kurz warten, wieder einschalten — hilft oft bei Routern und Geräten.',
     sv:'Att stänga av en enhet helt, vänta några sekunder och slå på den igen — löser ofta router-problem.'},
    {t:'Port', c:HW,
     en:'A physical socket on a device where you plug in a cable (USB port, HDMI port). In networking it also means a numbered channel.',
     de:'Eine Anschlussbuchse am Gerät (USB-Port, HDMI-Port). In Netzwerken auch ein nummerierter Kanal.',
     sv:'Ett uttag på en enhet där man kopplar in en kabel (USB-port, HDMI-port). I nätverk även en numrerad kanal.'},
    {t:'Dongle', c:HW,
     en:'A small adapter that plugs into a port to add a missing connection — e.g. USB-C to HDMI.',
     de:'Ein kleiner Adapter für einen fehlenden Anschluss — z. B. USB-C auf HDMI.',
     sv:'En liten adapter som ger en anslutning som saknas — t.ex. USB-C till HDMI.'},
    {t:'E-Ink', c:HW,
     en:'A paper-like screen technology (Kindle, reMarkable): easy on the eyes, great in sunlight, uses almost no power.',
     de:'Eine papierartige Bildschirmtechnik (Kindle, reMarkable): augenschonend, sonnenlichttauglich, extrem sparsam.',
     sv:'En pappersliknande skärmteknik (Kindle, reMarkable): skonsam för ögonen, bra i solljus, mycket strömsnål.'},
    {t:'NFC', c:HW,
     en:'Near Field Communication — the very-short-range radio behind tap-to-pay (Apple Pay) and tap-to-connect tags.',
     de:'Der Nahbereichsfunk hinter kontaktlosem Bezahlen (Apple Pay) und Antipp-Tags.',
     sv:'Närfältskommunikation — radiotekniken bakom kontaktlös betalning (Apple Pay) och tryck-taggar.'},
    {t:'Wearable', c:HW,
     en:'A computer you wear — smartwatch, fitness band, smart ring.',
     de:'Ein Computer zum Tragen — Smartwatch, Fitnessband, smarter Ring.',
     sv:'En dator du bär på kroppen — smartklocka, aktivitetsarmband, smart ring.'},
    {t:'Smart Home', c:HW,
     en:'Household devices (lights, thermostat, locks) connected to the internet and controllable from your phone.',
     de:'Haushaltsgeräte (Licht, Thermostat, Schlösser) mit Internetanbindung, steuerbar vom Handy.',
     sv:'Hushållsenheter (lampor, termostat, lås) som är uppkopplade och styrs från mobilen.'},

    // ---------- Software & Apps ----------
    {t:'Operating System (OS)', c:SW,
     en:'The base software that runs a device and all its apps — macOS, iOS, Windows, Android.',
     de:'Die Basissoftware, die ein Gerät und alle Apps betreibt — macOS, iOS, Windows, Android.',
     sv:'Grundprogramvaran som driver en enhet och alla dess appar — macOS, iOS, Windows, Android.'},
    {t:'Update vs. Upgrade', c:SW,
     en:'An update fixes and improves the version you have (17.1 → 17.2); an upgrade jumps to a new major version (17 → 18).',
     de:'Ein Update verbessert die vorhandene Version (17.1 → 17.2); ein Upgrade springt auf eine neue Hauptversion (17 → 18).',
     sv:'En update förbättrar versionen du har (17.1 → 17.2); en upgrade hoppar till en ny huvudversion (17 → 18).'},
    {t:'Patch', c:SW,
     en:'A small software fix released quickly, often to close a security hole.',
     de:'Eine kleine, schnell veröffentlichte Fehlerkorrektur, oft für Sicherheitslücken.',
     sv:'En liten programfix som släpps snabbt, ofta för att täppa till ett säkerhetshål.'},
    {t:'UI (User Interface)', c:SW,
     en:'Everything you see and touch in an app: buttons, menus, lists, colours.',
     de:'Alles, was man in einer App sieht und bedient: Knöpfe, Menüs, Listen, Farben.',
     sv:'Allt du ser och rör i en app: knappar, menyer, listor, färger.'},
    {t:'UX (User Experience)', c:SW,
     en:'How an app feels to use: is it clear, fast and pleasant, or confusing and frustrating?',
     de:'Wie sich eine App anfühlt: klar, schnell und angenehm — oder verwirrend und frustrierend?',
     sv:'Hur en app känns att använda: tydlig, snabb och trevlig — eller rörig och frustrerande?'},
    {t:'Widget', c:SW,
     en:'A small live view of an app placed on the home screen or desktop — weather, calendar, battery.',
     de:'Eine kleine Live-Ansicht einer App auf dem Home-Bildschirm oder Schreibtisch — Wetter, Kalender, Batterie.',
     sv:'En liten live-vy av en app på hemskärmen eller skrivbordet — väder, kalender, batteri.'},
    {t:'Notification', c:SW,
     en:'A message an app pushes to your screen to get your attention — banners, badges, sounds.',
     de:'Eine Meldung, die eine App auf den Bildschirm schickt — Banner, Kennzeichen, Töne.',
     sv:'Ett meddelande som en app skickar till din skärm — banderoller, märken, ljud.'},
    {t:'Toggle', c:SW,
     en:'An on/off switch in an app’s settings.',
     de:'Ein Ein/Aus-Schalter in den Einstellungen einer App.',
     sv:'En på/av-knapp i en apps inställningar.'},
    {t:'Dropdown Menu', c:SW,
     en:'A control that unfolds a list of choices when tapped.',
     de:'Ein Bedienelement, das beim Antippen eine Liste von Auswahlmöglichkeiten aufklappt.',
     sv:'En kontroll som fäller ut en lista med val när man trycker på den.'},
    {t:'Checkbox', c:SW,
     en:'A small square you tick to switch an option on or off; several can be ticked at once.',
     de:'Ein kleines Kästchen zum Anhaken einer Option; mehrere können gleichzeitig angehakt sein.',
     sv:'En liten ruta du bockar i för att slå på ett val; flera kan bockas i samtidigt.'},
    {t:'Slider', c:SW,
     en:'A control you drag along a line to set a value, like volume or brightness.',
     de:'Ein Regler, den man entlang einer Linie zieht, z. B. für Lautstärke oder Helligkeit.',
     sv:'En kontroll du drar längs en linje för att ställa in ett värde, som volym eller ljusstyrka.'},
    {t:'Dialog Box', c:SW,
     en:'A window that interrupts to ask something ("Delete? Cancel/OK") and waits for your answer.',
     de:'Ein Fenster, das mit einer Frage unterbricht („Löschen? Abbrechen/OK") und auf Antwort wartet.',
     sv:'Ett fönster som avbryter med en fråga ("Radera? Avbryt/OK") och väntar på ditt svar.'},
    {t:'Wizard / Assistant', c:SW,
     en:'A guided step-by-step setup, one question per screen — like when setting up a new iPhone.',
     de:'Eine geführte Schritt-für-Schritt-Einrichtung, eine Frage pro Bildschirm — wie beim neuen iPhone.',
     sv:'En guidad steg-för-steg-inställning, en fråga per skärm — som när man ställer in en ny iPhone.'},
    {t:'Plugin', c:SW,
     en:'An add-on that gives an app extra abilities it didn’t ship with.',
     de:'Eine Erweiterung, die einer App zusätzliche Fähigkeiten gibt.',
     sv:'Ett tillägg som ger en app extra förmågor den inte hade från början.'},
    {t:'Extension', c:SW,
     en:'A small add-on for the browser that changes or adds features — ad blockers, password managers.',
     de:'Ein kleines Browser-Add-on, das Funktionen ändert oder ergänzt — Werbeblocker, Passwortmanager.',
     sv:'Ett litet webbläsartillägg som ändrar eller lägger till funktioner — annonsblockerare, lösenordshanterare.'},
    {t:'Keyboard Shortcut', c:SW,
     en:'A key combination that triggers a command instantly, like ⌘C for copy.',
     de:'Eine Tastenkombination, die einen Befehl sofort auslöst, z. B. ⌘C für Kopieren.',
     sv:'En tangentkombination som utför ett kommando direkt, t.ex. ⌘C för kopiera.'},
    {t:'Drag and Drop', c:SW,
     en:'Moving something on screen by holding it, dragging it to a new place and letting go.',
     de:'Etwas am Bildschirm gedrückt halten, an eine neue Stelle ziehen und loslassen.',
     sv:'Att flytta något på skärmen genom att hålla, dra till en ny plats och släppa.'},
    {t:'Clipboard', c:SW,
     en:'The invisible storage where copied text or images wait until you paste them.',
     de:'Der unsichtbare Zwischenspeicher, in dem Kopiertes wartet, bis man es einfügt.',
     sv:'Det osynliga mellanlagret där kopierad text eller bilder väntar tills du klistrar in dem.'},
    {t:'Dark Mode', c:SW,
     en:'A display style with dark backgrounds and light text — easier on the eyes at night.',
     de:'Ein Anzeigestil mit dunklem Hintergrund und heller Schrift — abends angenehmer.',
     sv:'Ett visningsläge med mörk bakgrund och ljus text — skönare för ögonen på kvällen.'},
    {t:'Freemium', c:SW,
     en:'A pricing model: the basic app is free, extra features cost money.',
     de:'Ein Preismodell: Die Basis-App ist gratis, Extras kosten.',
     sv:'En prismodell: basappen är gratis, extrafunktioner kostar.'},
    {t:'Subscription', c:SW,
     en:'Paying for software monthly or yearly instead of buying it once.',
     de:'Software monatlich oder jährlich bezahlen statt einmalig kaufen.',
     sv:'Att betala för programvara per månad eller år i stället för att köpa den en gång.'},
    {t:'In-App Purchase', c:SW,
     en:'Something bought inside an app — extra features, coins, subscriptions.',
     de:'Ein Kauf innerhalb einer App — Zusatzfunktionen, Münzen, Abos.',
     sv:'Ett köp inuti en app — extrafunktioner, mynt, prenumerationer.'},
    {t:'License Key', c:SW,
     en:'A code that proves you bought software and unlocks it.',
     de:'Ein Code, der den Kauf einer Software belegt und sie freischaltet.',
     sv:'En kod som bevisar att du köpt programvaran och låser upp den.'},
    {t:'QR Code', c:SW,
     en:'A square barcode a camera can read; it usually opens a link. QR = Quick Response.',
     de:'Ein quadratischer Strichcode für die Kamera; öffnet meist einen Link.',
     sv:'En fyrkantig streckkod som kameran kan läsa; öppnar oftast en länk.'},
    {t:'OCR', c:SW,
     en:'Optical Character Recognition — software that reads text out of photos or scans so you can copy or search it.',
     de:'Texterkennung — Software, die Text aus Fotos oder Scans liest, damit man ihn kopieren und durchsuchen kann.',
     sv:'Textigenkänning — programvara som läser text ur foton eller inskanningar så att den kan kopieras och sökas.'},

    // ---------- AI ----------
    {t:'Artificial Intelligence (AI)', c:AI,
     en:'Computer systems that perform tasks that normally need human intelligence: understanding language, recognising images, reasoning.',
     de:'Computersysteme, die Aufgaben erledigen, die normalerweise menschliche Intelligenz erfordern: Sprache verstehen, Bilder erkennen, schlussfolgern.',
     sv:'Datorsystem som utför uppgifter som normalt kräver mänsklig intelligens: förstå språk, känna igen bilder, resonera.'},
    {t:'Machine Learning', c:AI,
     en:'A way of building AI where the computer learns patterns from examples instead of following hand-written rules.',
     de:'Ein KI-Ansatz, bei dem der Computer Muster aus Beispielen lernt, statt festen Regeln zu folgen.',
     sv:'Ett sätt att bygga AI där datorn lär sig mönster från exempel i stället för att följa handskrivna regler.'},
    {t:'LLM', c:AI,
     en:'Large Language Model — an AI trained on enormous amounts of text that can read and write language. Claude and ChatGPT are LLMs.',
     de:'Ein großes Sprachmodell — eine auf riesigen Textmengen trainierte KI, die Sprache lesen und schreiben kann. Claude und ChatGPT sind LLMs.',
     sv:'En stor språkmodell — en AI tränad på enorma textmängder som kan läsa och skriva språk. Claude och ChatGPT är LLM:er.'},
    {t:'Chatbot', c:AI,
     en:'A program you talk to in normal language, in text or voice — from simple support bots to AI assistants.',
     de:'Ein Programm, mit dem man in normaler Sprache schreibt oder spricht — vom Support-Bot bis zum KI-Assistenten.',
     sv:'Ett program du pratar med på vanligt språk, i text eller tal — från enkla supportbottar till AI-assistenter.'},
    {t:'Prompt', c:AI,
     en:'The instruction or question you give an AI. Better prompts get better answers.',
     de:'Die Anweisung oder Frage an eine KI. Bessere Prompts liefern bessere Antworten.',
     sv:'Instruktionen eller frågan du ger en AI. Bättre prompter ger bättre svar.'},
    {t:'Prompt Engineering', c:AI,
     en:'The craft of writing prompts that reliably get an AI to do what you want.',
     de:'Die Kunst, Prompts so zu formulieren, dass eine KI zuverlässig das Gewünschte tut.',
     sv:'Hantverket att skriva prompter som får en AI att göra det du vill, på ett pålitligt sätt.'},
    {t:'Token', c:AI,
     en:'The small chunks of text an AI actually processes — roughly word pieces. AI usage and cost are counted in tokens.',
     de:'Die kleinen Textstücke, die eine KI tatsächlich verarbeitet — etwa Wortteile. Nutzung und Kosten werden in Tokens gezählt.',
     sv:'De små textbitar en AI faktiskt bearbetar — ungefär orddelar. Användning och kostnad räknas i tokens.'},
    {t:'Context Window', c:AI,
     en:'How much text an AI can "hold in mind" at once. When a conversation exceeds it, the AI starts forgetting the beginning.',
     de:'Wie viel Text eine KI gleichzeitig „im Kopf behalten" kann. Wird es mehr, vergisst sie den Anfang.',
     sv:'Hur mycket text en AI kan "hålla i huvudet" samtidigt. Blir samtalet längre börjar den glömma början.'},
    {t:'Hallucination', c:AI,
     en:'When an AI confidently states something that is simply not true. Always double-check important facts.',
     de:'Wenn eine KI selbstbewusst etwas behauptet, das schlicht nicht stimmt. Wichtige Fakten immer prüfen.',
     sv:'När en AI självsäkert påstår något som helt enkelt inte stämmer. Dubbelkolla alltid viktiga fakta.'},
    {t:'Training Data', c:AI,
     en:'The examples (text, images, code) an AI model learned from.',
     de:'Die Beispiele (Text, Bilder, Code), aus denen ein KI-Modell gelernt hat.',
     sv:'Exemplen (text, bilder, kod) som en AI-modell har lärt sig av.'},
    {t:'Neural Network', c:AI,
     en:'The mathematical structure inside modern AI, loosely inspired by how neurons connect in the brain.',
     de:'Die mathematische Struktur moderner KI, lose inspiriert von den Nervenzellen des Gehirns.',
     sv:'Den matematiska strukturen i modern AI, löst inspirerad av hjärnans nervceller.'},
    {t:'Deep Learning', c:AI,
     en:'Machine learning with many-layered neural networks — the technique behind today’s AI boom.',
     de:'Maschinelles Lernen mit vielschichtigen neuronalen Netzen — die Technik hinter dem heutigen KI-Boom.',
     sv:'Maskininlärning med neurala nätverk i många lager — tekniken bakom dagens AI-våg.'},
    {t:'Generative AI', c:AI,
     en:'AI that creates new content — text, images, music, video, code — rather than only analysing existing content.',
     de:'KI, die neue Inhalte erschafft — Text, Bilder, Musik, Video, Code — statt nur Vorhandenes zu analysieren.',
     sv:'AI som skapar nytt innehåll — text, bilder, musik, video, kod — i stället för att bara analysera.'},
    {t:'Fine-Tuning', c:AI,
     en:'Taking a trained AI model and training it a bit more on specific material to specialise it.',
     de:'Ein fertig trainiertes KI-Modell mit speziellem Material nachtrainieren, um es zu spezialisieren.',
     sv:'Att vidareträna en färdig AI-modell på specifikt material för att specialisera den.'},
    {t:'AI Agent', c:AI,
     en:'An AI that doesn’t just answer but acts: it can use tools, browse, edit files and work through multi-step tasks on its own.',
     de:'Eine KI, die nicht nur antwortet, sondern handelt: Werkzeuge nutzen, Dateien bearbeiten, mehrschrittige Aufgaben selbstständig erledigen.',
     sv:'En AI som inte bara svarar utan agerar: använder verktyg, redigerar filer och löser fleregsuppgifter på egen hand.'},
    {t:'Claude', c:AI,
     en:'The AI assistant made by Anthropic. Claude Code is the version that builds and edits software — it built this app.',
     de:'Der KI-Assistent von Anthropic. Claude Code ist die Variante, die Software baut — auch diese App.',
     sv:'AI-assistenten från Anthropic. Claude Code är varianten som bygger programvara — den byggde den här appen.'},
    {t:'ChatGPT', c:AI,
     en:'The AI chatbot made by OpenAI that started the current AI wave in late 2022.',
     de:'Der KI-Chatbot von OpenAI, der Ende 2022 die aktuelle KI-Welle auslöste.',
     sv:'AI-chattboten från OpenAI som startade den nuvarande AI-vågen i slutet av 2022.'},
    {t:'Model', c:AI,
     en:'One specific trained AI, with a name and version — like "Claude Sonnet" or "GPT-5". New models replace old ones like app versions.',
     de:'Eine konkrete trainierte KI mit Name und Version — etwa „Claude Sonnet". Neue Modelle lösen alte ab wie App-Versionen.',
     sv:'En specifik tränad AI med namn och version — som "Claude Sonnet". Nya modeller ersätter gamla som appversioner.'},
    {t:'Multimodal', c:AI,
     en:'An AI that handles more than text — it can also see images, hear audio or watch video.',
     de:'Eine KI, die mehr als Text kann — auch Bilder sehen, Audio hören oder Video verstehen.',
     sv:'En AI som hanterar mer än text — den kan också se bilder, höra ljud eller förstå video.'},
    {t:'Speech Recognition', c:AI,
     en:'Technology that turns spoken words into text — dictation, Siri, meeting transcripts.',
     de:'Technik, die gesprochene Worte in Text verwandelt — Diktat, Siri, Meeting-Protokolle.',
     sv:'Teknik som gör talade ord till text — diktering, Siri, mötestranskript.'},
    {t:'Text-to-Speech', c:AI,
     en:'Technology that reads text aloud with a synthetic voice.',
     de:'Technik, die Text mit synthetischer Stimme vorliest.',
     sv:'Teknik som läser upp text med en syntetisk röst.'},
    {t:'AGI', c:AI,
     en:'Artificial General Intelligence — a hypothetical AI as capable as a human across essentially all thinking tasks. Doesn’t exist yet.',
     de:'Künstliche Allgemeine Intelligenz — eine hypothetische KI, die bei praktisch allen Denkaufgaben menschliches Niveau erreicht. Gibt es noch nicht.',
     sv:'Artificiell generell intelligens — en hypotetisk AI lika kapabel som en människa på i princip alla tankeuppgifter. Finns inte än.'},

    // ---------- Cloud & Data ----------
    {t:'The Cloud', c:CLOUD,
     en:'Other people’s computers: services and storage running in data centres, reached over the internet instead of on your own device.',
     de:'„Die Computer anderer Leute": Dienste und Speicher in Rechenzentren, erreichbar übers Internet statt auf dem eigenen Gerät.',
     sv:'Andras datorer: tjänster och lagring i datacenter som nås via internet i stället för på din egen enhet.'},
    {t:'Cloud Storage', c:CLOUD,
     en:'Saving files on internet servers (iCloud Drive, Dropbox, Google Drive) so all your devices see them.',
     de:'Dateien auf Internet-Servern speichern (iCloud Drive, Dropbox, Google Drive), sodass alle Geräte sie sehen.',
     sv:'Att spara filer på internetservrar (iCloud Drive, Dropbox, Google Drive) så att alla dina enheter ser dem.'},
    {t:'iCloud', c:CLOUD,
     en:'Apple’s cloud service: it syncs photos, files, notes, passwords and backups across your Apple devices.',
     de:'Apples Cloud-Dienst: synchronisiert Fotos, Dateien, Notizen, Passwörter und Backups über alle Apple-Geräte.',
     sv:'Apples molntjänst: synkar foton, filer, anteckningar, lösenord och säkerhetskopior mellan dina Apple-enheter.'},
    {t:'Sync', c:CLOUD,
     en:'Keeping the same data identical on several devices: change it on the iPhone, and the Mac shows the change too.',
     de:'Dieselben Daten auf mehreren Geräten identisch halten: am iPhone geändert, zeigt es auch der Mac.',
     sv:'Att hålla samma data identisk på flera enheter: ändra på din iPhone, och din Mac visar ändringen också.'},
    {t:'Backup', c:CLOUD,
     en:'A safety copy of your data, stored separately, so nothing is lost if a device breaks. A backup you’ve never test-restored is not a backup.',
     de:'Eine Sicherheitskopie der Daten, getrennt aufbewahrt. Ein nie testweise zurückgespieltes Backup ist kein Backup.',
     sv:'En säkerhetskopia av din data, lagrad separat. En backup som aldrig test-återställts är ingen backup.'},
    {t:'Database', c:CLOUD,
     en:'An organised store of data that programs can search and update quickly — like a super-powered filing cabinet.',
     de:'Ein geordneter Datenspeicher, den Programme schnell durchsuchen und ändern können.',
     sv:'Ett organiserat datalager som program snabbt kan söka i och uppdatera.'},
    {t:'Server', c:CLOUD,
     en:'A computer that provides a service to other computers — hosting websites, storing mail, syncing files. Usually runs day and night in a data centre.',
     de:'Ein Computer, der anderen Computern einen Dienst bereitstellt — Websites, Mail, Dateisync. Läuft meist rund um die Uhr im Rechenzentrum.',
     sv:'En dator som tillhandahåller tjänster åt andra datorer — webbplatser, e-post, filsynk. Kör oftast dygnet runt i ett datacenter.'},
    {t:'Data Center', c:CLOUD,
     en:'A building full of servers where cloud services physically live.',
     de:'Ein Gebäude voller Server, in dem Cloud-Dienste physisch zu Hause sind.',
     sv:'En byggnad full av servrar där molntjänster fysiskt bor.'},
    {t:'Export / Import', c:CLOUD,
     en:'Export writes your data out of an app into a file; import reads such a file back in. The universal way to move data between apps.',
     de:'Export schreibt Daten aus einer App in eine Datei; Import liest so eine Datei wieder ein.',
     sv:'Export skriver ut din data från en app till en fil; import läser in en sådan fil igen.'},
    {t:'CSV', c:CLOUD,
     en:'Comma-Separated Values — a plain-text table format that Excel, Numbers and most apps can open.',
     de:'Ein einfaches Text-Tabellenformat, das Excel, Numbers und die meisten Apps öffnen können.',
     sv:'Ett enkelt texttabellformat som Excel, Numbers och de flesta appar kan öppna.'},
    {t:'Metadata', c:CLOUD,
     en:'Data about data: a photo’s date, location and camera settings are metadata of the image.',
     de:'Daten über Daten: Datum, Ort und Kameraeinstellungen eines Fotos sind seine Metadaten.',
     sv:'Data om data: ett fotos datum, plats och kamerainställningar är bildens metadata.'},
    {t:'File Format', c:CLOUD,
     en:'The type of a file, shown by its ending: .jpg photo, .pdf document, .json data. The format decides which apps can open it.',
     de:'Der Typ einer Datei, erkennbar an der Endung: .jpg Foto, .pdf Dokument, .json Daten.',
     sv:'En fils typ, som syns på ändelsen: .jpg foto, .pdf dokument, .json data.'},
    {t:'ZIP / Compression', c:CLOUD,
     en:'Packing files into a smaller archive file (.zip) for storage or sending; unzipping unpacks them again.',
     de:'Dateien in ein kleineres Archiv (.zip) packen zum Speichern oder Versenden; Entpacken macht es rückgängig.',
     sv:'Att packa filer till ett mindre arkiv (.zip) för lagring eller sändning; uppackning gör tvärtom.'},
    {t:'Gigabyte / Terabyte', c:CLOUD,
     en:'Storage sizes: 1 GB ≈ 1000 photos’ worth of "small" files; 1 TB = 1000 GB.',
     de:'Speichergrößen: 1 GB ist grob tausend kleinere Dateien; 1 TB = 1000 GB.',
     sv:'Lagringsstorlekar: 1 GB rymmer grovt tusen mindre filer; 1 TB = 1000 GB.'},
    {t:'Local Storage', c:CLOUD,
     en:'Data stored on the device itself rather than in the cloud. Works offline; lost if only the device dies without backup.',
     de:'Daten auf dem Gerät selbst statt in der Cloud. Funktioniert offline; ohne Backup weg, wenn das Gerät stirbt.',
     sv:'Data lagrad på själva enheten i stället för i molnet. Fungerar offline; förloras utan backup om enheten dör.'},
    {t:'IndexedDB', c:CLOUD,
     en:'The browser’s built-in database where web apps store larger data (lists, photos) on the device. AMS apps keep their data here.',
     de:'Die eingebaute Datenbank des Browsers, in der Web-Apps größere Daten am Gerät speichern. AMS-Apps speichern hier.',
     sv:'Webbläsarens inbyggda databas där webbappar lagrar större data på enheten. AMS-apparna sparar sin data här.'},
    {t:'API Key', c:CLOUD,
     en:'A secret code that identifies you to an online service, like a personal entrance ticket. Never share it publicly.',
     de:'Ein geheimer Code, der dich bei einem Online-Dienst ausweist — wie eine persönliche Eintrittskarte. Nie öffentlich teilen.',
     sv:'En hemlig kod som identifierar dig hos en onlinetjänst — som en personlig entrébiljett. Dela den aldrig offentligt.'},
    {t:'Dashboard', c:CLOUD,
     en:'A single screen showing the most important numbers and statuses at a glance, like a car’s instrument panel.',
     de:'Eine Übersichtsseite mit den wichtigsten Zahlen und Statusanzeigen auf einen Blick — wie das Armaturenbrett im Auto.',
     sv:'En översiktssida som visar de viktigaste siffrorna och statusarna på en gång — som instrumentpanelen i en bil.'},
    {t:'Big Data', c:CLOUD,
     en:'Data sets so large that ordinary tools can’t handle them — analysed to find patterns and trends.',
     de:'Datenmengen, die für normale Werkzeuge zu groß sind — analysiert, um Muster und Trends zu finden.',
     sv:'Datamängder så stora att vanliga verktyg inte klarar dem — analyseras för att hitta mönster och trender.'},

    // ---------- Security & Privacy ----------
    {t:'Passkey', c:SEC,
     en:'The modern replacement for passwords: your device proves who you are with Face ID or Touch ID; there’s nothing to remember or steal.',
     de:'Der moderne Passwort-Ersatz: Das Gerät weist dich per Face ID oder Touch ID aus; nichts zu merken, nichts zu stehlen.',
     sv:'Den moderna ersättaren för lösenord: din enhet bevisar vem du är med Face ID eller Touch ID; inget att minnas eller stjäla.'},
    {t:'Two-Factor Authentication (2FA)', c:SEC,
     en:'Logging in with two proofs: something you know (password) plus something you have (a code on your phone). Stops most account theft.',
     de:'Anmeldung mit zwei Nachweisen: etwas, das man weiß (Passwort), plus etwas, das man hat (Code am Handy).',
     sv:'Inloggning med två bevis: något du vet (lösenord) plus något du har (en kod på mobilen).'},
    {t:'Encryption', c:SEC,
     en:'Scrambling data so only someone with the right key can read it.',
     de:'Daten so verschlüsseln, dass nur der richtige Schlüssel sie lesbar macht.',
     sv:'Att kryptera data så att bara den med rätt nyckel kan läsa den.'},
    {t:'End-to-End Encryption', c:SEC,
     en:'Only sender and receiver can read the messages — not even the service in between (e.g. iMessage, Signal).',
     de:'Nur Absender und Empfänger können die Nachrichten lesen — nicht einmal der Dienst dazwischen (z. B. iMessage, Signal).',
     sv:'Bara avsändare och mottagare kan läsa meddelandena — inte ens tjänsten däremellan (t.ex. iMessage, Signal).'},
    {t:'VPN', c:SEC,
     en:'Virtual Private Network — an encrypted tunnel for your internet traffic. Hides your activity from the local network and your location from websites.',
     de:'Ein verschlüsselter Tunnel für den Internetverkehr. Verbirgt Aktivität vor dem lokalen Netz und den Standort vor Websites.',
     sv:'En krypterad tunnel för din internettrafik. Döljer aktivitet för det lokala nätet och din plats för webbplatser.'},
    {t:'Firewall', c:SEC,
     en:'A guard that watches network traffic and blocks connections that aren’t allowed.',
     de:'Ein Wächter, der den Netzwerkverkehr überwacht und unerlaubte Verbindungen blockiert.',
     sv:'En vakt som övervakar nätverkstrafik och blockerar otillåtna anslutningar.'},
    {t:'Phishing', c:SEC,
     en:'Fake emails or websites that imitate real ones to trick you into entering passwords or card numbers. Check the sender and the URL.',
     de:'Gefälschte E-Mails oder Websites, die echte imitieren, um Passwörter oder Kartendaten abzugreifen. Absender und URL prüfen!',
     sv:'Falska mejl eller webbplatser som härmar riktiga för att lura av dig lösenord eller kortuppgifter. Kontrollera avsändare och URL.'},
    {t:'Malware', c:SEC,
     en:'Malicious software of any kind: viruses, spyware, ransomware.',
     de:'Schadsoftware jeder Art: Viren, Spyware, Ransomware.',
     sv:'Skadlig programvara av alla slag: virus, spionprogram, utpressningsprogram.'},
    {t:'Ransomware', c:SEC,
     en:'Malware that encrypts your files and demands payment to unlock them. Good backups are the best defence.',
     de:'Schadsoftware, die Dateien verschlüsselt und Lösegeld fordert. Gute Backups sind die beste Verteidigung.',
     sv:'Skadeprogram som krypterar dina filer och kräver betalning. Bra säkerhetskopior är bästa försvaret.'},
    {t:'Spam', c:SEC,
     en:'Unwanted mass messages, mostly email advertising or scams.',
     de:'Unerwünschte Massennachrichten, meist Werbung oder Betrug per E-Mail.',
     sv:'Oönskade massmeddelanden, mest reklam eller bedrägerier via mejl.'},
    {t:'CAPTCHA', c:SEC,
     en:'The "prove you’re not a robot" test — clicking traffic lights or typing warped letters.',
     de:'Der „Ich bin kein Roboter"-Test — Ampeln anklicken oder verzerrte Buchstaben abtippen.',
     sv:'Testet "bevisa att du inte är en robot" — klicka på trafikljus eller skriva förvrängda bokstäver.'},
    {t:'Biometrics', c:SEC,
     en:'Using your body to unlock things: fingerprint (Touch ID), face (Face ID), voice.',
     de:'Den Körper zum Entsperren nutzen: Fingerabdruck (Touch ID), Gesicht (Face ID), Stimme.',
     sv:'Att använda kroppen för att låsa upp: fingeravtryck (Touch ID), ansikte (Face ID), röst.'},
    {t:'Password Manager', c:SEC,
     en:'An app that stores all your passwords in one encrypted vault and fills them in for you (1Password, Apple Passwords).',
     de:'Eine App, die alle Passwörter verschlüsselt aufbewahrt und automatisch einsetzt (1Password, Apple Passwörter).',
     sv:'En app som förvarar alla lösenord i ett krypterat valv och fyller i dem åt dig (1Password, Apple Lösenord).'},
    {t:'Data Breach', c:SEC,
     en:'When a company’s stored user data is stolen or leaked. If a service you use is breached, change that password.',
     de:'Wenn gespeicherte Nutzerdaten einer Firma gestohlen oder geleakt werden. Betroffen? Passwort ändern.',
     sv:'När ett företags lagrade användardata stjäls eller läcker. Berörd tjänst? Byt det lösenordet.'},
    {t:'Permissions', c:SEC,
     en:'What an app is allowed to access — camera, microphone, location, contacts. You grant or refuse each one.',
     de:'Worauf eine App zugreifen darf — Kamera, Mikrofon, Standort, Kontakte. Jede Freigabe erteilst du selbst.',
     sv:'Vad en app får komma åt — kamera, mikrofon, plats, kontakter. Du beviljar eller nekar varje del.'},
    {t:'Tracking', c:SEC,
     en:'Following what you do across apps and websites, usually to target advertising at you.',
     de:'Verfolgen, was du über Apps und Websites hinweg tust — meist für zielgerichtete Werbung.',
     sv:'Att följa vad du gör i appar och på webbplatser, oftast för riktad reklam.'},
    {t:'Ad Blocker', c:SEC,
     en:'A browser extension that stops ads (and much of their tracking) from loading.',
     de:'Eine Browser-Erweiterung, die Werbung (und viel Tracking) am Laden hindert.',
     sv:'Ett webbläsartillägg som hindrar reklam (och mycket av dess spårning) från att laddas.'},
    {t:'Authentication', c:SEC,
     en:'Proving you are who you claim to be — by password, passkey, code or fingerprint.',
     de:'Nachweisen, dass man ist, wer man vorgibt zu sein — per Passwort, Passkey, Code oder Fingerabdruck.',
     sv:'Att bevisa att du är den du utger dig för att vara — med lösenord, passkey, kod eller fingeravtryck.'},
    {t:'Zero-Day', c:SEC,
     en:'A security hole that attackers found before the maker did — so there were "zero days" to prepare a fix. Why prompt updates matter.',
     de:'Eine Sicherheitslücke, die Angreifer vor dem Hersteller fanden — null Tage Zeit für einen Fix. Darum zügig updaten.',
     sv:'Ett säkerhetshål som angripare hittade före tillverkaren — noll dagar att förbereda en fix. Därför är snabba uppdateringar viktiga.'},

    // ---------- Networking ----------
    {t:'Wi-Fi', c:NET,
     en:'Wireless network technology that connects devices to a router and thus the internet, within a home or building.',
     de:'Drahtlose Netzwerktechnik, die Geräte mit dem Router und damit dem Internet verbindet.',
     sv:'Trådlös nätverksteknik som kopplar enheter till en router och därmed internet.'},
    {t:'Router', c:NET,
     en:'The box that distributes your internet connection to all devices, by Wi-Fi and cable, and directs the traffic between them.',
     de:'Die Box, die den Internetanschluss per WLAN und Kabel an alle Geräte verteilt und den Verkehr lenkt.',
     sv:'Lådan som fördelar din internetanslutning till alla enheter, via Wi-Fi och kabel, och dirigerar trafiken.'},
    {t:'Modem', c:NET,
     en:'The device that connects your home to the internet provider’s line. Often built into the same box as the router.',
     de:'Das Gerät, das das Zuhause mit der Leitung des Internetanbieters verbindet. Oft mit dem Router in einer Box.',
     sv:'Enheten som kopplar hemmet till internetleverantörens ledning. Ofta inbyggd i samma låda som routern.'},
    {t:'Ethernet', c:NET,
     en:'Wired network connection via cable — less convenient than Wi-Fi but faster and rock-stable.',
     de:'Kabelgebundene Netzwerkverbindung — unbequemer als WLAN, aber schneller und absolut stabil.',
     sv:'Trådbunden nätverksanslutning via kabel — mindre bekväm än Wi-Fi men snabbare och stensäker.'},
    {t:'IP Address', c:NET,
     en:'The numeric address of a device on a network, like 192.168.1.5 — the network’s equivalent of a street address.',
     de:'Die numerische Adresse eines Geräts im Netzwerk, z. B. 192.168.1.5 — die Hausadresse im Netz.',
     sv:'En enhets numeriska adress i ett nätverk, t.ex. 192.168.1.5 — nätets motsvarighet till en gatuadress.'},
    {t:'DNS', c:NET,
     en:'The internet’s phone book: it translates names like apple.com into the numeric IP addresses computers actually use.',
     de:'Das Telefonbuch des Internets: übersetzt Namen wie apple.com in die numerischen IP-Adressen.',
     sv:'Internets telefonkatalog: översätter namn som apple.com till de numeriska IP-adresser datorer använder.'},
    {t:'Hotspot', c:NET,
     en:'Sharing a phone’s mobile internet with other devices over Wi-Fi — "Personal Hotspot" on the iPhone.',
     de:'Das mobile Internet des Handys per WLAN mit anderen Geräten teilen — am iPhone „Persönlicher Hotspot".',
     sv:'Att dela mobilens internet med andra enheter via Wi-Fi — "Internetdelning" på iPhone.'},
    {t:'Roaming', c:NET,
     en:'Using your phone on a foreign network abroad. Within the EU it costs nothing extra; elsewhere it can be expensive.',
     de:'Das Handy im ausländischen Netz nutzen. In der EU ohne Aufpreis, anderswo teils teuer.',
     sv:'Att använda mobilen i ett utländskt nät. Inom EU utan extra kostnad, på andra håll kan det bli dyrt.'},
    {t:'5G / LTE (4G)', c:NET,
     en:'Generations of mobile internet. LTE/4G is the reliable standard; 5G is newer and faster where available.',
     de:'Mobilfunk-Generationen. LTE/4G ist der verlässliche Standard; 5G ist neuer und schneller, wo verfügbar.',
     sv:'Generationer av mobilt internet. LTE/4G är den pålitliga standarden; 5G är nyare och snabbare där det finns.'},
    {t:'Bandwidth', c:NET,
     en:'How much data a connection can move per second — the "width of the pipe". Measured in Mbps.',
     de:'Wie viel Daten eine Verbindung pro Sekunde transportiert — die „Dicke des Rohrs". Gemessen in Mbit/s.',
     sv:'Hur mycket data en anslutning kan flytta per sekund — "rörets bredd". Mäts i Mbps.'},
    {t:'Latency / Ping', c:NET,
     en:'The delay before data starts flowing, in milliseconds. Low latency matters for video calls and gaming.',
     de:'Die Verzögerung, bis Daten fließen, in Millisekunden. Wichtig für Videocalls und Spiele.',
     sv:'Fördröjningen innan data börjar flöda, i millisekunder. Låg latens är viktigt för videosamtal och spel.'},
    {t:'Mbps', c:NET,
     en:'Megabits per second — the unit of internet speed. 100 Mbps is comfortable for a household; note: 8 megabits = 1 megabyte.',
     de:'Megabit pro Sekunde — die Einheit der Internetgeschwindigkeit. 8 Megabit = 1 Megabyte.',
     sv:'Megabit per sekund — enheten för internethastighet. 8 megabit = 1 megabyte.'},
    {t:'SSID', c:NET,
     en:'The name of a Wi-Fi network — what you see in the Wi-Fi list.',
     de:'Der Name eines WLAN-Netzes — das, was in der WLAN-Liste steht.',
     sv:'Namnet på ett Wi-Fi-nätverk — det du ser i Wi-Fi-listan.'},
    {t:'Mesh Network', c:NET,
     en:'Several Wi-Fi stations spread through the house acting as one network, removing dead corners.',
     de:'Mehrere WLAN-Stationen im Haus, die als ein Netz auftreten und Funklöcher beseitigen.',
     sv:'Flera Wi-Fi-stationer i huset som fungerar som ett nätverk och tar bort döda vinklar.'},
    {t:'Tethering', c:NET,
     en:'Connecting a computer to the internet through your phone, by cable or hotspot.',
     de:'Einen Computer übers Handy ins Internet bringen, per Kabel oder Hotspot.',
     sv:'Att koppla en dator till internet via mobilen, med kabel eller hotspot.'},
    {t:'Offline / Online', c:NET,
     en:'Online = connected to the internet; offline = not connected. Offline-capable apps (like this one) keep working without any connection.',
     de:'Online = mit Internet verbunden; offline = ohne Verbindung. Offline-fähige Apps (wie diese) funktionieren auch ohne Netz.',
     sv:'Online = ansluten till internet; offline = utan anslutning. Offlinekapabla appar (som denna) fungerar även utan nät.'},
    {t:'Bluetooth Pairing', c:NET,
     en:'The one-time "introduction" of two Bluetooth devices so they trust and auto-connect to each other from then on.',
     de:'Das einmalige „Bekanntmachen" zweier Bluetooth-Geräte, damit sie sich künftig automatisch verbinden.',
     sv:'Den engångs-"presentation" av två Bluetooth-enheter så att de sedan litar på varandra och ansluter automatiskt.'},
    {t:'AirTag / Tracker', c:NET,
     en:'A small tag that reports its location over a finding network, to keep track of keys, luggage or a bike.',
     de:'Ein kleiner Anhänger, der seinen Standort über ein Suchnetzwerk meldet — für Schlüssel, Gepäck, Fahrrad.',
     sv:'En liten bricka som rapporterar sin plats via ett hittanätverk — för nycklar, bagage eller cykeln.'},

    // ---------- Mac & iPhone ----------
    {t:'macOS', c:APPLE,
     en:'The operating system of the Mac. Versions carry California names — Sequoia, Sonoma, Ventura.',
     de:'Das Betriebssystem des Mac. Versionen tragen kalifornische Namen — Sequoia, Sonoma, Ventura.',
     sv:'Macens operativsystem. Versionerna bär kaliforniska namn — Sequoia, Sonoma, Ventura.'},
    {t:'iOS / iPadOS', c:APPLE,
     en:'The operating systems of iPhone and iPad, updated yearly with a new major version number.',
     de:'Die Betriebssysteme von iPhone und iPad, jährlich mit neuer Hauptversion.',
     sv:'Operativsystemen för iPhone och iPad, uppdateras årligen med nytt huvudversionsnummer.'},
    {t:'Finder', c:APPLE,
     en:'The Mac’s file manager — the app with the smiling face icon where you browse folders and files.',
     de:'Die Dateiverwaltung des Mac — das Programm mit dem lächelnden Gesicht für Ordner und Dateien.',
     sv:'Macens filhanterare — programmet med den leende ikonen där du bläddrar bland mappar och filer.'},
    {t:'Dock', c:APPLE,
     en:'The row of app icons at the bottom edge of the Mac screen (and the bar on iPhone/iPad) for launching and switching apps.',
     de:'Die Symbolleiste am unteren Bildschirmrand des Mac (bzw. iPhone/iPad) zum Starten und Wechseln von Apps.',
     sv:'Raden med appikoner längst ner på Mac-skärmen (och fältet på iPhone/iPad) för att starta och byta appar.'},
    {t:'Spotlight', c:APPLE,
     en:'The Mac/iPhone system search: ⌘Space (or swipe down) finds apps, files, contacts and does quick math.',
     de:'Die Systemsuche: ⌘Leertaste (oder Wisch nach unten) findet Apps, Dateien, Kontakte und rechnet.',
     sv:'Systemsökningen: ⌘Mellanslag (eller svep nedåt) hittar appar, filer, kontakter och räknar snabbt.'},
    {t:'Menu Bar', c:APPLE,
     en:'The strip along the top of the Mac screen with the Apple menu, app menus, clock and status icons.',
     de:'Die Leiste am oberen Mac-Bildschirmrand mit Apple-Menü, App-Menüs, Uhr und Statussymbolen.',
     sv:'Listen högst upp på Mac-skärmen med Apple-menyn, appmenyer, klocka och statusikoner.'},
    {t:'AirDrop', c:APPLE,
     en:'Apple’s instant wireless file sharing between nearby iPhones, iPads and Macs.',
     de:'Apples direkte Funkübertragung von Dateien zwischen iPhones, iPads und Macs in der Nähe.',
     sv:'Apples direkta trådlösa fildelning mellan iPhones, iPads och Mac-datorer i närheten.'},
    {t:'AirPlay', c:APPLE,
     en:'Wirelessly sending video or audio from an Apple device to a TV or speaker.',
     de:'Video oder Audio drahtlos vom Apple-Gerät an TV oder Lautsprecher senden.',
     sv:'Att trådlöst skicka video eller ljud från en Apple-enhet till en TV eller högtalare.'},
    {t:'Handoff / Continuity', c:APPLE,
     en:'Starting something on one Apple device and continuing on another — write an email on the iPhone, finish on the Mac.',
     de:'Auf einem Apple-Gerät beginnen, auf einem anderen weitermachen — E-Mail am iPhone anfangen, am Mac beenden.',
     sv:'Att börja något på en Apple-enhet och fortsätta på en annan — skriv mejlet på din iPhone, avsluta på din Mac.'},
    {t:'Control Center', c:APPLE,
     en:'The panel of quick switches (Wi-Fi, brightness, flashlight) — swipe down from the top-right corner on iPhone.',
     de:'Das Feld mit Schnellschaltern (WLAN, Helligkeit, Taschenlampe) — am iPhone von rechts oben herunterwischen.',
     sv:'Panelen med snabbreglage (Wi-Fi, ljusstyrka, ficklampa) — svep ner från övre högra hörnet på iPhone.'},
    {t:'App Store', c:APPLE,
     en:'Apple’s official shop for apps. Everything in it is checked by Apple before publication.',
     de:'Apples offizieller App-Laden. Alles darin wird vor Veröffentlichung von Apple geprüft.',
     sv:'Apples officiella butik för appar. Allt i den granskas av Apple före publicering.'},
    {t:'TestFlight', c:APPLE,
     en:'Apple’s app for trying beta versions of apps before they reach the App Store.',
     de:'Apples App zum Testen von Beta-Versionen, bevor sie in den App Store kommen.',
     sv:'Apples app för att testa betaversioner av appar innan de når App Store.'},
    {t:'Apple Shortcuts', c:APPLE,
     en:'Apple’s automation app: chain actions into one-tap routines, e.g. "start the cold-shower timer at 6 minutes".',
     de:'Apples Automatisierungs-App: Aktionen zu Ein-Tipp-Routinen verketten, z. B. „Kaltdusch-Timer mit 6 Minuten starten".',
     sv:'Apples automatiseringsapp: kedja ihop åtgärder till ett-trycks-rutiner, t.ex. "starta kalldusch-timern på 6 minuter".'},
    {t:'Time Machine', c:APPLE,
     en:'The Mac’s built-in backup: it continuously saves versions of everything to an external drive so you can go back in time.',
     de:'Das eingebaute Mac-Backup: sichert laufend Versionen auf eine externe Platte — man kann „in der Zeit zurückreisen".',
     sv:'Macens inbyggda backup: sparar löpande versioner till en extern disk så att du kan gå tillbaka i tiden.'},
    {t:'Keychain', c:APPLE,
     en:'Apple’s built-in password vault that syncs via iCloud and autofills logins on all your devices.',
     de:'Apples eingebauter Passwort-Tresor, der über iCloud synchronisiert und Logins automatisch ausfüllt.',
     sv:'Apples inbyggda lösenordsvalv som synkas via iCloud och fyller i inloggningar på alla dina enheter.'},
    {t:'Add to Home Screen', c:APPLE,
     en:'Safari’s way of installing a web app: Share button → "Add to Home Screen" puts an icon on the iPhone that opens the app full-screen. How every AMS app is installed.',
     de:'Safaris Weg, eine Web-App zu installieren: Teilen → „Zum Home-Bildschirm". So wird jede AMS-App installiert.',
     sv:'Safaris sätt att installera en webbapp: Dela-knappen → "Lägg till på hemskärmen". Så installeras varje AMS-app.'},
    {t:'Force Quit', c:APPLE,
     en:'Forcefully closing a frozen app: ⌥⌘Esc on the Mac; on iPhone swipe up and flick the app away.',
     de:'Eine eingefrorene App zwangsweise beenden: ⌥⌘Esc am Mac; am iPhone hochwischen und App wegschieben.',
     sv:'Att tvångsstänga en app som hängt sig: ⌥⌘Esc på Mac; på iPhone svep upp och för bort appen.'},
    {t:'Screenshot', c:APPLE,
     en:'A photo of what’s on the screen. iPhone: side button + volume up. Mac: ⇧⌘3 (whole screen) or ⇧⌘4 (selection).',
     de:'Ein Foto des Bildschirminhalts. iPhone: Seitentaste + Lauter. Mac: ⇧⌘3 (alles) oder ⇧⌘4 (Ausschnitt).',
     sv:'Ett foto av det som visas på skärmen. iPhone: sidoknapp + volym upp. Mac: ⇧⌘3 (hela) eller ⇧⌘4 (urval).'},
    {t:'Live Text', c:APPLE,
     en:'Apple’s built-in OCR: text inside photos can be selected, copied and translated directly.',
     de:'Apples eingebaute Texterkennung: Text in Fotos lässt sich direkt markieren, kopieren und übersetzen.',
     sv:'Apples inbyggda textigenkänning: text i foton kan markeras, kopieras och översättas direkt.'},
    {t:'Focus Mode', c:APPLE,
     en:'iPhone/Mac profiles that silence chosen notifications for chosen times — Do Not Disturb, Work, Sleep.',
     de:'Profile, die bestimmte Mitteilungen zu bestimmten Zeiten stummschalten — Nicht stören, Arbeit, Schlafen.',
     sv:'Profiler som tystar valda notiser vid valda tider — Stör ej, Arbete, Sömn.'},
    {t:'Face ID / Touch ID', c:APPLE,
     en:'Apple’s biometric unlock: Face ID scans your face, Touch ID your fingerprint — for unlocking, paying and passwords.',
     de:'Apples biometrische Entsperrung: Face ID scannt das Gesicht, Touch ID den Fingerabdruck.',
     sv:'Apples biometriska upplåsning: Face ID läser ansiktet, Touch ID fingeravtrycket — för upplåsning, betalning och lösenord.'},
    {t:'Sideloading', c:APPLE,
     en:'Installing an app from outside the official app store. Common on Android; on iPhone only possible in limited ways.',
     de:'Eine App außerhalb des offiziellen Stores installieren. Auf Android üblich, am iPhone nur eingeschränkt möglich.',
     sv:'Att installera en app utanför den officiella butiken. Vanligt på Android; på iPhone bara möjligt i begränsad form.'}
    ];
})();
